version: "3.7"
services:
  flask_app:
    build: './flask_app'
    restart: always
    ports:
      - "5050:5050"
    command: /usr/local/bin/gunicorn -w 1 -b 0.0.0.0:5050 wsgi:app

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "81:81"
    depends_on:
      - flask_app