version: "3.7"
services:
  flask_app:
    build: './flask_app'
    restart: always
    ports:
      - "5000:5000"
    command: /usr/local/bin/gunicorn -w 9 -b 0.0.0.0:5000 wsgi:app

  nginx:
    build: ./nginx
    #container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask_app